name: media_core_ffi
description: A high-performance offline on-device AI Gallery app powered by SigLIP, Whisper, PP-OCR, and ObjectBox DB.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.2
  path_provider: ^2.1.1
  objectbox: ^4.0.0
  flutter_dotenv: ^5.1.0
  crypto: ^3.0.3
  photo_manager: ^3.11.0
  receive_sharing_intent: ^1.9.0
  flutter_foreground_task: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  objectbox_generator: ^4.0.0
  build_runner: ^2.4.6

dependency_overrides:
  source_gen: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
